language: elixir
elixir:
  - 1.0.4
otp_release:
  - 17.3
sudo: true
before_script:
  - sudo pip install crossbar[msgpack]
  - export PLT_FILENAME=elixir-1.0.4_17.3.plt
  - export PLT_LOCATION=/home/travis/$PLT_FILENAME
  - wget -O $PLT_LOCATION https://raw.github.com/danielberkompas/travis_elixir_plts/master/$PLT_FILENAME
script:
  - mix test.all && mix spell.example.pubsub > /dev/null && mix spell.example.rpc > /dev/null
  - dialyzer --no_check_plt --plt $PLT_LOCATION --no_native _build/test/lib/spell/ebin
after_success:
  - pkill -f crossbar
notifications:
  recipients:
    - jtmoulia@gmail.com
    - tanzi.marco@gmail.com
    - volker.rabe@gmail.com
    - danmarcab@gmail.com
